version: '3'
services:
  backend:
    build: ./backend
    environment:
      MONGODB_CONNECTION_STRING: 'mongodb://host.docker.internal:27017/twt_clone'
      PORT: '3000'
    ports:
      - 3000:3000
    volumes: 
      - ./backend:/backend
  frontend:
    build: ./frontend
    environment:
      VUE_APP_API_URL: 'http://localhost:3000'
      RANDOM_USER_API: 'https://randomuser.me/api/?nat=tr&inc=name'
      PORT: '8080'
    ports:
      - 8080:8080
    volumes: 
      - ./frontend:/frontend

  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017
